/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IRiskEngine {
    function checkVolatility(uint256[] memory prices, uint256 threshold_bps) external returns (bool);

    function computeVariance(uint256[] memory prices) external returns (uint256);

    function lastVariance() external view returns (uint256);

    function lastMean() external view returns (uint256);

    function lastCount() external view returns (uint256);
}
